name: check
on:
  workflow_call:
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --check --all
  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Install sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run sccache stat for check
        run: ${SCCACHE_PATH} --show-stats
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings
  doc:
    runs-on: ubuntu-latest
    name: nightly / doc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run sccache stat for check
        run: ${SCCACHE_PATH} --show-stats
      - name: cargo doc
        run: cargo doc --no-deps --all-features --workspace
        env:
          RUSTDOCFLAGS: --cfg docsrs -D warnings
  hack:
    runs-on: ubuntu-latest
    name: ubuntu / stable / features
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run sccache stat for check
        run: ${SCCACHE_PATH} --show-stats
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack
        run: cargo hack --workspace --feature-powerset check
  minimal:
    runs-on: ubuntu-latest
    name: ubuntu / stable / minimal-versions
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install nightly for -Zminimal-versions
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo hack
        uses: taiki-e/install-action@cargo-hack
      - name: Install cargo minimal-versions
        uses: taiki-e/install-action@cargo-minimal-versions
      - name: Install sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run sccache stat for check
        run: ${SCCACHE_PATH} --show-stats
      - name: rustup default stable
        run: rustup default stable
      - name: Check minimal versions
        run: cargo minimal-versions check --workspace --ignore-private --detach-path-deps --direct
  # msrv:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       msrv: [1.56.1] # 2021 edition requires 1.56
  #   name: ubuntu / ${{ matrix.msrv }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: Install ${{ matrix.msrv }}
  #       uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: ${{ matrix.msrv }}
  #     - name: Install sccache-cache
  #       uses: mozilla-actions/sccache-action@v0.0.9
  #     - name: Run sccache stat for check
  #       run: ${SCCACHE_PATH} --show-stats
  #     - name: cargo +${{ matrix.msrv }} check
  #       run: cargo check --workspace
